#include "main.h"

void move_ab();
void move_al();
void move_ah();
void move_am();
void move_ba();
void move_bl();
void move_bh();
void move_bm();
void move_la();
void move_lb();
void move_lh();
void move_lm();
void move_ha();
void move_hb();
void move_hl();
void move_hm();
void move_ma();
void move_mb();
void move_ml();
void move_mh();
